/* ============================================================
   01_BRONZE_LOAD.SQL
   Layer   : BRONZE
   Purpose : Land raw source files into Snowflake exactly as they
             arrive from source systems — no cleaning, no typing
             beyond what the file format needs, no business logic.
             Bronze is a raw, replayable mirror of the source.

   Idempotency: COPY INTO tracks already-loaded files by file name
   by default in Snowflake, so re-running this script against the
   same stage will not duplicate rows.
   ============================================================ */

CREATE SCHEMA IF NOT EXISTS bronze;

CREATE FILE FORMAT IF NOT EXISTS bronze.csv_ff
  TYPE = CSV
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('', 'N/A', 'NULL')
  EMPTY_FIELD_AS_NULL = TRUE;

-- Points at wherever the source extracts land (S3 / Azure / internal stage).
CREATE STAGE IF NOT EXISTS bronze.aml_stage
  FILE_FORMAT = bronze.csv_ff;

/* ---------------------------------------------------------
   raw_customer  (source: Onboarding / KYC system)
--------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS bronze.raw_customer (
  customer_id               VARCHAR,
  full_name                 VARCHAR,
  dob                       DATE,
  ssn_id_number             VARCHAR,
  country                   VARCHAR,
  occupation_business_type  VARCHAR,
  pep_flag                  BOOLEAN,
  risk_rating               VARCHAR,
  onboarding_date           DATE,
  kyc_review_date           DATE,
  source_system             VARCHAR,
  load_timestamp            TIMESTAMP_NTZ
);

COPY INTO bronze.raw_customer
FROM @bronze.aml_stage/raw_customer/
FILE_FORMAT = bronze.csv_ff
ON_ERROR = 'CONTINUE'
PURGE = FALSE;

/* ---------------------------------------------------------
   raw_account  (source: Core Banking)
--------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS bronze.raw_account (
  account_id      VARCHAR,
  customer_id     VARCHAR,
  account_type    VARCHAR,
  open_date       DATE,
  status          VARCHAR,
  source_system   VARCHAR,
  load_timestamp  TIMESTAMP_NTZ
);

COPY INTO bronze.raw_account
FROM @bronze.aml_stage/raw_account/
FILE_FORMAT = bronze.csv_ff
ON_ERROR = 'CONTINUE'
PURGE = FALSE;

/* ---------------------------------------------------------
   raw_transactions  (source: Core Banking — largest table)
--------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS bronze.raw_transactions (
  transaction_id         VARCHAR,
  account_id             VARCHAR,
  counterparty_id        VARCHAR,
  counterparty_name      VARCHAR,
  counterparty_country   VARCHAR,
  amount                 NUMBER(18,2),
  currency               VARCHAR,
  channel                VARCHAR,
  direction              VARCHAR,
  transaction_timestamp  TIMESTAMP_NTZ,
  source_system          VARCHAR,
  load_timestamp         TIMESTAMP_NTZ
);

COPY INTO bronze.raw_transactions
FROM @bronze.aml_stage/raw_transactions/
FILE_FORMAT = bronze.csv_ff
ON_ERROR = 'CONTINUE'
PURGE = FALSE;

/* ---------------------------------------------------------
   raw_rule  (hand-authored rule engine configuration — not an
   external feed. Drives every threshold used by the gold-layer
   detection engine in 04, so nothing downstream is hardcoded.)
--------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS bronze.raw_rule (
  rule_id           VARCHAR,
  rule_name         VARCHAR,
  rule_type         VARCHAR,
  threshold_params  VARIANT,
  effective_date    DATE
);

COPY INTO bronze.raw_rule
FROM @bronze.aml_stage/raw_rule/
FILE_FORMAT = bronze.csv_ff
ON_ERROR = 'CONTINUE'
PURGE = FALSE;
-- threshold_params lands as VARCHAR from CSV. It is cast to VARIANT with
-- PARSE_JSON downstream in silver/gold, not at load time, so bronze stays
-- a raw mirror of source rather than a partially-typed hybrid.

/* ---------------------------------------------------------
   raw_watchlist  (source: public OFAC SDN sample feed)
--------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS bronze.raw_watchlist (
  watchlist_id  VARCHAR,
  entity_name   VARCHAR,
  entity_type   VARCHAR,
  country       VARCHAR,
  program       VARCHAR,
  list_date     DATE
);

COPY INTO bronze.raw_watchlist
FROM @bronze.aml_stage/raw_watchlist/
FILE_FORMAT = bronze.csv_ff
ON_ERROR = 'CONTINUE'
PURGE = FALSE;

/* NOTE: there is intentionally no bronze.raw_alerts table. Alerts are not
   sourced externally — they are generated by the rule engine in
   04_gold_rule_engine.sql. A "raw_alerts" bronze table would misrepresent
   where that data actually comes from. */
